version: "3.7"
services:
  app:
    build:
      args:
        user: 1000
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ${DOCKER_APP_NAME}
    container_name: ${DOCKER_APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
   # command: sh -c "composer install"
    networks:
      - realtime

  db:
    image: mysql:5.7
    container_name: ${DOCKER_APP_NAME}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
#      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - realtime

  nginx:
    image: nginx:1.17-alpine
    container_name: ${DOCKER_APP_NAME}-nginx
    working_dir: /var/www
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/:ro
    networks:
      - realtime

  node:
    image: node:14-alpine
    working_dir: /app
    container_name: node
    restart: unless-stopped
    volumes:
      - ./:/app
    depends_on:
      - 'app'
    command: sh -c "npm install && npm run watch"
    networks:
      - realtime
networks:
  realtime:
    driver: bridge

volumes:
  db-data:
